# Generated by Django 5.2.1 on 2025-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.TextField(),
        ),
    ]
