# Generated by Django 5.2.1 on 2025-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('article_type', models.CharField(max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
